<gardenplan>
  <plan title="my plan" gridSize="11.1111111" gridWidth="1500" gridHeight="1500" version="3.0"/>
  <objects>
    <item obType="tool" id="-1" x="400" y="47" width="309.35" height="4.5" rotation="0" title="wall" description="" currentFillColour="0" depth="0" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="1" distBetweenObjects="0" toolArrayX="-132.85,171.35" toolArrayY="0,0.5" curveArrayX="" curveArrayY=""/>
    <item obType="tool" id="-1" x="265" y="184" width="5" height="588.85" rotation="0" title="wall" description="" currentFillColour="0" depth="1" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="1" distBetweenObjects="0" toolArrayX="1,2" toolArrayY="-136.85,445.85" curveArrayX="" curveArrayY=""/>
    <item obType="tool" id="-1" x="571" y="184" width="5.5" height="586.85" rotation="0" title="wall" description="" currentFillColour="0" depth="2" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="1" distBetweenObjects="0" toolArrayX="1,2.5" toolArrayY="-135.85,444.85" curveArrayX="" curveArrayY=""/>
    <item obType="object" id="210" x="522" y="631" width="93.85" height="175.7" rotation="0" title="door%0A%20style%20%231" description="" currentFillColour="16777215" depth="0" depthType="4" currentFlowerColour="" locked="false" inReport="true"/>
    <item obType="object" id="152" x="390" y="236" width="236.5" height="167.9" rotation="0" title="double%20bed" description="" currentFillColour="16777215" depth="3" depthType="3" currentFlowerColour="3355443" locked="false" inReport="true"/>
    <item obType="tool" id="-1" x="401" y="632" width="309.85" height="4.5" rotation="0" title="wall" description="" currentFillColour="0" depth="4" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="1" distBetweenObjects="0" toolArrayX="-132.85,171.85" toolArrayY="0,0.5" curveArrayX="" curveArrayY=""/>
    <item obType="tool" id="-1" x="401" y="447" width="270.7" height="4" rotation="0" title="wall" description="" currentFillColour="0" depth="5" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="1" distBetweenObjects="0" toolArrayX="-132.85,-47.15" toolArrayY="0,0" curveArrayX="" curveArrayY=""/>
    <item obType="tool" id="-1" x="354" y="580.5" width="5" height="135.35" rotation="0" title="wall" description="" currentFillColour="0" depth="6" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="1" distBetweenObjects="0" toolArrayX="0,1" toolArrayY="-132.85,-24.15" curveArrayX="" curveArrayY=""/>
    <item obType="tool" id="-1" x="100" y="100" width="274.65" height="8" rotation="0" title="thick%20wall" description="" currentFillColour="0" depth="7" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="3" distBetweenObjects="0" toolArrayX="-133.825,133.825" toolArrayY="0,0" curveArrayX="" curveArrayY=""/>
    <item obType="tool" id="-1" x="553.5" y="556.5" width="201.45" height="4.5" rotation="0" title="wall" description="" currentFillColour="0" depth="8" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="1" distBetweenObjects="0" toolArrayX="-98.35,-47.15" toolArrayY="-0.5,0" curveArrayX="" curveArrayY=""/>
    <item obType="tool" id="-1" x="460" y="689.5" width="5" height="244.75" rotation="0" title="wall" description="" currentFillColour="0" depth="9" depthType="3" currentFlowerColour="" locked="false" inReport="true" plantType="houseFixtures" toolMode="line" toolNum="2" numTools="1" shapeType="-1" toolStyle="1" distBetweenObjects="0" toolArrayX="-1,0" toolArrayY="-241.85,-57.15" curveArrayX="" curveArrayY=""/>
    <item obType="object" id="209" x="417" y="47" width="156" height="28" rotation="180" title="french%20doors" description="" currentFillColour="16777215" depth="1" depthType="4" currentFlowerColour="" locked="false" inReport="true"/>
    <item obType="object" id="9" x="291" y="113" width="38" height="60" rotation="0" title="square" description="" currentFillColour="16777215" depth="10" depthType="3" currentFlowerColour="" locked="false" inReport="true"/>
    <item obType="object" id="9" x="292" y="356" width="38" height="60" rotation="0" title="square" description="" currentFillColour="16777215" depth="11" depthType="3" currentFlowerColour="" locked="false" inReport="true"/>
    <item obType="object" id="9" x="501" y="73" width="124" height="38" rotation="0" title="square" description="" currentFillColour="16777215" depth="12" depthType="3" currentFlowerColour="" locked="false" inReport="true"/>
  </objects>
  <notes/>
</gardenplan>